### ISSUE TITLE
[post-idea] 10 checkers you should use even if you hate Coding Standards

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.cz#157]
The selection

```yaml
checkers:
    PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer:
        syntax: short
    - SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff
    - PhpCsFixer\Fixer\Import\NoUnusedImportsFixer
    - PhpCsFixer\Fixer\Import\OrderedImportsFixer
    - Symplify\CodingStandard\Fixer\Php\ClassStringToClassConstantFixer
```
