### ISSUE TITLE
[layout] related_external_sources

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.cz#301]
**To promote external sources** without a need to mention them in the post.

In a post headline:

```yaml
id: 5
related_items: [3]
related_external_sources:
    http://paul-m-jones.com/archives/6589: http://paul-m-jones.com/archives/6589: "Action Injection As A Code Smell"
```

Write in `post.latte`

```html
{if count($related_external_sources)}
    <hr class="mt-4 mb-lg-5">

    Do you want more on this topic by other authors? You might like these <strong>related posts</strong>:

    {foreach $related_external_sources as $url => $name}
        <a href="{$url}">{$name}</a>{sep}, {/sep}
    {/foreach}
{/if}
```
